-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 12:01:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestor` (
  `codID` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Palete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Palete` (
  `codID` VARCHAR(5) NOT NULL,
  `refrigerado` TINYINT NOT NULL,
  `conteudo` VARCHAR(45) NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `codID` VARCHAR(5) NOT NULL,
  `tipo` TINYINT NOT NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conteudo` (
  `Pedido_codID` VARCHAR(5) NOT NULL,
  `Palete_codID` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Pedido_codID`, `Palete_codID`),
  INDEX `fk_Pedido_has_Palete_Palete1_idx` (`Palete_codID` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Palete_Pedido_idx` (`Pedido_codID` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Palete_Pedido`
    FOREIGN KEY (`Pedido_codID`)
    REFERENCES `mydb`.`Pedido` (`codID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Palete_Palete1`
    FOREIGN KEY (`Palete_codID`)
    REFERENCES `mydb`.`Palete` (`codID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Robots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Robots` (
  `codID` VARCHAR(5) NOT NULL,
  `ordens_feitas` INT ZEROFILL NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
