-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 12:01:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET GLOBAL time_zone = '+0:00';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `armazem` DEFAULT CHARACTER SET utf8 ;
USE `armazem` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armazem`.`Gestor` (
  `codID` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Palete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armazem`.`Palete` (
  `codID` VARCHAR(5) NOT NULL,
  `refrigerado` TINYINT NOT NULL,
  `conteudo` VARCHAR(45) NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armazem`.`Entrega` (
  `codID` VARCHAR(5) NOT NULL,
  `conteudo` VARCHAR(90) NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Palete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armazem`.`Requisicao` (
  `codID` VARCHAR(5) NOT NULL,
  `conteudo` VARCHAR(90) NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Robots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armazem`.`Robots` (
  `codID` VARCHAR(5) NOT NULL,
  `ordens_feitas` INT ZEROFILL NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
